project:
  type: website
  output-dir: docs
website:
  title: "Μαθηματικά Γυμνασίου & Λυκείου"

  navbar:
    left:
      - text: Γυμνάσιο
        menu:
          - text: Α Τάξη
            href: gymnasio/a/index.qmd
          - text: Β Τάξη
            href: gymnasio/b/index.qmd
          - text: Γ Τάξη
            href: gymnasio/g/index.qmd
           
          
            

      - text: Λύκειο
        menu:
          - text: Α' Λυκείου
            href: lykeio/a/index.qmd
          - text: Β' Λυκείου
            href: lykeio/b/index.qmd
          - text: Γ' Λυκείου
            href: lykeio/g/index.qmd

  sidebar:
    style: "floating"
    contents:
      - auto: true

format:
  html:
    theme: cosmo
    toc: true
    toc-depth: 3
    number-sections: true
